title: Default Page
extends: options/base_options

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          headerImage:
            label: Header Image
            type: files
            max: 1
            layout: cards
            uploads:
              parent: page
              accept:
                extension: [jpg, jpeg, png, webp]

          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Unterseiten
      files:
        type: files

